import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Opportunity from '../models/Opportunity.js';
import Exam from '../models/Exam.js';

dotenv.config();

const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/careerlinks';

// Sample Internships Data
const internshipsData = [
    {
        title: 'Software Engineering Intern',
        company: 'Google India',
        type: 'Internship',
        category: 'IT',
        description: 'Join Google\'s engineering team to work on cutting-edge products. You will collaborate with experienced engineers and contribute to real projects that impact millions of users worldwide.',
        eligibility: 'B.Tech/BE in CS/IT, 3rd or 4th year students. Strong programming skills in Python, Java, or C++.',
        stipend: '₹80,000/month',
        duration: '6 months',
        workType: 'Hybrid',
        applyLink: 'https://careers.google.com/jobs/results/?employment_type=INTERN',
        deadline: new Date('2025-06-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Data Science Intern',
        company: 'Microsoft India',
        type: 'Internship',
        category: 'IT',
        description: 'Work with Microsoft\'s AI and data science teams on machine learning models, data pipelines, and analytics solutions for enterprise clients.',
        eligibility: 'Pursuing B.Tech/MTech in CS/Data Science. Knowledge of ML, Python, and SQL required.',
        stipend: '₹75,000/month',
        duration: '6 months',
        workType: 'Remote',
        applyLink: 'https://careers.microsoft.com/students/us/en/us-intern',
        deadline: new Date('2025-07-15'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Product Management Intern',
        company: 'Amazon India',
        type: 'Internship',
        category: 'Management',
        description: 'Assist product managers in defining product roadmaps, conducting market research, and analyzing user feedback for Amazon\'s e-commerce platform.',
        eligibility: 'MBA students or B.Tech with strong analytical skills. Experience with data analysis tools preferred.',
        stipend: '₹70,000/month',
        duration: '3 months',
        workType: 'On-site',
        applyLink: 'https://www.amazon.jobs/content/en/teams/internships',
        deadline: new Date('2025-05-30'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Marketing Intern',
        company: 'Flipkart',
        type: 'Internship',
        category: 'E-commerce',
        description: 'Support Flipkart\'s digital marketing campaigns, social media strategy, and customer engagement initiatives across multiple channels.',
        eligibility: 'Pursuing MBA in Marketing or BBA. Creative mindset and social media savvy.',
        stipend: '₹35,000/month',
        duration: '3 months',
        workType: 'Hybrid',
        applyLink: 'https://www.flipkartcareers.com/',
        deadline: new Date('2025-06-15'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Finance Analyst Intern',
        company: 'Goldman Sachs',
        type: 'Internship',
        category: 'Finance',
        description: 'Assist in financial modeling, market research, and investment analysis. Work with senior analysts on real client projects and portfolio management.',
        eligibility: 'Pursuing CA/CFA/MBA Finance. Strong Excel and financial modeling skills.',
        stipend: '₹60,000/month',
        duration: '6 months',
        workType: 'On-site',
        applyLink: 'https://www.goldmansachs.com/careers/students',
        deadline: new Date('2025-07-01'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'UI/UX Design Intern',
        company: 'Adobe India',
        type: 'Internship',
        category: 'IT',
        description: 'Collaborate with design teams to create intuitive user interfaces for Adobe Creative Cloud products. Conduct user research and prototype designs.',
        eligibility: 'Design students or B.Tech with design portfolio. Proficiency in Figma and Adobe XD.',
        stipend: '₹45,000/month',
        duration: '6 months',
        workType: 'Hybrid',
        applyLink: 'https://careers.adobe.com/us/en',
        deadline: new Date('2025-08-15'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Content Writing Intern',
        company: 'BYJU\'S',
        type: 'Internship',
        category: 'English Learning',
        description: 'Create engaging educational content for K-12 students. Develop lesson plans, quizzes, and interactive learning materials.',
        eligibility: 'English Literature or Education students. Strong writing and communication skills.',
        stipend: '₹25,000/month',
        duration: '3 months',
        workType: 'Remote',
        applyLink: 'https://byjus.com/careers/',
        deadline: new Date('2025-06-20'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Government Relations Intern',
        company: 'NITI Aayog',
        type: 'Internship',
        category: 'Government',
        description: 'Support policy research and analysis at India\'s premier think tank. Work on national development projects and policy recommendations.',
        eligibility: 'Graduate/Postgraduate students in Economics, Public Policy, or Law. Strong research skills.',
        stipend: '₹20,000/month',
        duration: '3 months',
        workType: 'On-site',
        applyLink: 'https://www.niti.gov.in/',
        deadline: new Date('2025-05-15'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Business Development Intern',
        company: 'Zomato',
        type: 'Internship',
        category: 'E-commerce',
        description: 'Assist in expanding Zomato\'s restaurant partner network. Conduct market analysis and support partnership negotiations.',
        eligibility: 'Business students with strong communication skills. Sales experience is a plus.',
        stipend: '₹30,000/month',
        duration: '6 months',
        workType: 'Hybrid',
        applyLink: 'https://www.zomato.com/careers',
        deadline: new Date('2025-07-30'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Research Intern',
        company: 'ISRO',
        type: 'Internship',
        category: 'Other',
        description: 'Contribute to space research projects at India\'s space agency. Work on satellite technology, remote sensing, or space exploration missions.',
        eligibility: 'B.Tech/MTech in Aerospace, Electronics, or Physics. Strong academic record required.',
        stipend: '₹25,000/month',
        duration: '6 months',
        workType: 'On-site',
        applyLink: 'https://www.isro.gov.in/Careers.html',
        deadline: new Date('2025-08-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
];

// Sample Jobs Data
const jobsData = [
    {
        title: 'Software Developer',
        company: 'TCS',
        type: 'Job',
        category: 'IT',
        description: 'Develop and maintain enterprise-level software applications. Work with Java, Spring Boot, and cloud technologies to deliver scalable solutions.',
        eligibility: 'B.Tech/BE in CS/IT with 0-2 years experience. Knowledge of Java and SQL.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'Hybrid',
        applyLink: 'https://www.tcs.com/careers',
        deadline: new Date('2025-06-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Data Analyst',
        company: 'Infosys',
        type: 'Job',
        category: 'IT',
        description: 'Analyze complex datasets to derive business insights. Create dashboards, reports, and predictive models to support decision-making.',
        eligibility: 'B.Tech/BCA with 0-3 years experience. Proficiency in SQL, Python, and Tableau.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'Remote',
        applyLink: 'https://www.infosys.com/careers',
        deadline: new Date('2025-07-15'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'HR Manager',
        company: 'Wipro',
        type: 'Job',
        category: 'Management',
        description: 'Lead recruitment, employee engagement, and talent management initiatives. Develop HR policies and manage organizational development programs.',
        eligibility: 'MBA in HR with 2-5 years experience. Strong interpersonal and leadership skills.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'On-site',
        applyLink: 'https://careers.wipro.com/',
        deadline: new Date('2025-06-15'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Financial Analyst',
        company: 'HDFC Bank',
        type: 'Job',
        category: 'Finance',
        description: 'Perform financial planning, budgeting, and forecasting. Analyze market trends and prepare investment recommendations for clients.',
        eligibility: 'CA/MBA Finance with 1-3 years experience. Advanced Excel and financial modeling skills.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'On-site',
        applyLink: 'https://www.hdfcbank.com/personal/about-us/careers',
        deadline: new Date('2025-07-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Digital Marketing Specialist',
        company: 'Myntra',
        type: 'Job',
        category: 'E-commerce',
        description: 'Plan and execute digital marketing campaigns across SEO, SEM, social media, and email marketing. Analyze campaign performance and optimize ROI.',
        eligibility: 'MBA Marketing or B.Tech with 1-4 years digital marketing experience.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'Hybrid',
        applyLink: 'https://www.myntra.com/careers',
        deadline: new Date('2025-08-15'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Civil Services Officer',
        company: 'Government of India',
        type: 'Job',
        category: 'Government',
        description: 'Serve the nation as an IAS, IPS, or IFS officer. Lead administrative functions, policy implementation, and public service delivery.',
        eligibility: 'Indian citizen with graduation degree. Must clear UPSC Civil Services Exam.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'On-site',
        applyLink: 'https://upsc.gov.in/',
        deadline: new Date('2025-03-15'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'English Language Trainer',
        company: 'British Council',
        type: 'Job',
        category: 'English Learning',
        description: 'Teach English language skills to students and professionals. Develop curriculum and conduct assessments for language proficiency.',
        eligibility: 'MA English or TEFL/TESOL certified. 2+ years teaching experience.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'On-site',
        applyLink: 'https://www.britishcouncil.in/careers',
        deadline: new Date('2025-07-01'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Cloud Architect',
        company: 'AWS India',
        type: 'Job',
        category: 'IT',
        description: 'Design and implement cloud infrastructure solutions for enterprise clients. Lead migration projects and optimize cloud architecture.',
        eligibility: 'B.Tech with 5+ years experience. AWS Solutions Architect certification required.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'Hybrid',
        applyLink: 'https://www.amazon.jobs/content/en/teams/amazon-web-services',
        deadline: new Date('2025-09-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Investment Banker',
        company: 'JP Morgan Chase',
        type: 'Job',
        category: 'Finance',
        description: 'Advise clients on mergers, acquisitions, and capital raising. Conduct financial due diligence and valuation analysis.',
        eligibility: 'MBA Finance or CA with 3-7 years experience. Strong financial modeling skills.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'On-site',
        applyLink: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/',
        deadline: new Date('2025-08-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Operations Manager',
        company: 'Reliance Industries',
        type: 'Job',
        category: 'Management',
        description: 'Oversee daily operations, supply chain management, and process optimization. Lead cross-functional teams to achieve operational excellence.',
        eligibility: 'MBA Operations or Engineering with 4-8 years experience. Lean Six Sigma certification preferred.',
        stipend: 'Not Applicable',
        duration: 'Permanent',
        workType: 'On-site',
        applyLink: 'https://careers.ril.com/',
        deadline: new Date('2025-07-20'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
];

// Sample Courses Data
const coursesData = [
    {
        title: 'Full Stack Web Development',
        company: 'Udemy',
        type: 'Course',
        category: 'IT',
        description: 'Master MERN stack development with React, Node.js, Express, and MongoDB. Build real-world projects and deploy them to the cloud.',
        eligibility: 'No prior experience required. Basic computer knowledge.',
        stipend: 'Not Applicable',
        duration: '6 months',
        workType: 'Remote',
        applyLink: 'https://www.udemy.com/topic/web-development/',
        deadline: new Date('2025-12-31'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Data Science Specialization',
        company: 'Coursera (Stanford)',
        type: 'Course',
        category: 'IT',
        description: 'Comprehensive data science program covering Python, machine learning, deep learning, and big data analytics. Industry-recognized certification.',
        eligibility: 'Basic programming knowledge. Mathematics and statistics fundamentals.',
        stipend: 'Not Applicable',
        duration: '8 months',
        workType: 'Remote',
        applyLink: 'https://www.coursera.org/specializations/data-science',
        deadline: new Date('2025-11-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Digital Marketing Masterclass',
        company: 'Google Digital Garage',
        type: 'Course',
        category: 'E-commerce',
        description: 'Learn SEO, SEM, social media marketing, content strategy, and analytics. Free certification from Google.',
        eligibility: 'No prerequisites. Suitable for beginners and professionals.',
        stipend: 'Not Applicable',
        duration: '3 months',
        workType: 'Remote',
        applyLink: 'https://learndigital.withgoogle.com/digitalgarage',
        deadline: new Date('2025-12-31'),
        isPaid: false,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Financial Modeling & Valuation',
        company: 'Wall Street Prep',
        type: 'Course',
        category: 'Finance',
        description: 'Master financial modeling, DCF valuation, and M&A analysis. Used by top investment banks and private equity firms.',
        eligibility: 'Finance background preferred. Excel proficiency required.',
        stipend: 'Not Applicable',
        duration: '2 months',
        workType: 'Remote',
        applyLink: 'https://www.wallstreetprep.com/',
        deadline: new Date('2025-10-15'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Project Management Professional',
        company: 'PMI',
        type: 'Course',
        category: 'Management',
        description: 'PMP certification preparation course. Covers project lifecycle, agile methodologies, risk management, and stakeholder communication.',
        eligibility: '3+ years project management experience. Bachelor\'s degree.',
        stipend: 'Not Applicable',
        duration: '4 months',
        workType: 'Remote',
        applyLink: 'https://www.pmi.org/certifications/project-management-pmp',
        deadline: new Date('2025-09-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'UPSC Civil Services Preparation',
        company: 'Unacademy',
        type: 'Course',
        category: 'Government',
        description: 'Comprehensive UPSC preparation with live classes, study material, test series, and mentorship from former civil servants.',
        eligibility: 'Graduation degree. Commitment to 12-18 months preparation.',
        stipend: 'Not Applicable',
        duration: '12 months',
        workType: 'Remote',
        applyLink: 'https://unacademy.com/goal/upsc-cse',
        deadline: new Date('2025-06-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Business English Communication',
        company: 'British Council',
        type: 'Course',
        category: 'English Learning',
        description: 'Improve professional English communication skills. Covers presentations, email writing, negotiations, and cross-cultural communication.',
        eligibility: 'Intermediate English level. Working professionals preferred.',
        stipend: 'Not Applicable',
        duration: '3 months',
        workType: 'Remote',
        applyLink: 'https://www.britishcouncil.in/english/courses-adults',
        deadline: new Date('2025-12-31'),
        isPaid: true,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'AWS Solutions Architect',
        company: 'Amazon Web Services',
        type: 'Course',
        category: 'IT',
        description: 'Prepare for AWS Solutions Architect Associate certification. Learn cloud architecture, EC2, S3, RDS, and serverless computing.',
        eligibility: 'Basic IT knowledge. Cloud computing fundamentals helpful.',
        stipend: 'Not Applicable',
        duration: '3 months',
        workType: 'Remote',
        applyLink: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
        deadline: new Date('2025-11-15'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
    {
        title: 'Stock Market Trading',
        company: 'Zerodha Varsity',
        type: 'Course',
        category: 'Finance',
        description: 'Free comprehensive stock market education. Learn technical analysis, fundamental analysis, options trading, and portfolio management.',
        eligibility: 'No prerequisites. Open to all interested in stock markets.',
        stipend: 'Not Applicable',
        duration: '2 months',
        workType: 'Remote',
        applyLink: 'https://zerodha.com/varsity/',
        deadline: new Date('2025-12-31'),
        isPaid: false,
        isHighlighted: false,
        isActive: true,
    },
    {
        title: 'Machine Learning A-Z',
        company: 'Udacity',
        type: 'Course',
        category: 'IT',
        description: 'Hands-on machine learning course covering regression, classification, clustering, NLP, and deep learning with Python and TensorFlow.',
        eligibility: 'Python programming required. Basic math and statistics knowledge.',
        stipend: 'Not Applicable',
        duration: '4 months',
        workType: 'Remote',
        applyLink: 'https://www.udacity.com/course/machine-learning-engineer-nanodegree--nd009t',
        deadline: new Date('2025-10-30'),
        isPaid: true,
        isHighlighted: true,
        isActive: true,
    },
];

// Sample Exams Data
const examsData = [
    {
        examTitle: 'UPSC Civil Services Examination 2025',
        organization: 'Union Public Service Commission',
        category: 'UPSC',
        description: 'India\'s most prestigious civil services exam for recruitment to IAS, IPS, IFS, and other central services. Three-stage selection process including Prelims, Mains, and Interview.',
        eligibility: 'Indian citizen with Bachelor\'s degree. Age: 21-32 years (General category).',
        examPattern: 'Prelims: 2 objective papers (GS + CSAT). Mains: 9 descriptive papers. Interview: Personality test.',
        syllabusLink: 'https://upsc.gov.in/examinations/syllabus',
        applyLink: 'https://upsconline.nic.in/',
        notificationLink: 'https://upsc.gov.in/examinations/exam-calendar',
        registrationStartDate: new Date('2025-02-01'),
        registrationLastDate: new Date('2025-02-21'),
        examDate: new Date('2025-05-25'),
        admitCardDate: new Date('2025-05-10'),
        resultDate: new Date('2025-08-15'),
        status: 'Active',
        notification: 'Active-Form',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'SSC CGL 2025',
        organization: 'Staff Selection Commission',
        category: 'SSC',
        description: 'Combined Graduate Level examination for recruitment to Group B and C posts in various ministries, departments, and organizations of the Government of India.',
        eligibility: 'Bachelor\'s degree from recognized university. Age: 18-32 years.',
        examPattern: 'Tier-I: Computer Based Test (Quant, Reasoning, English, GK). Tier-II: CBT + Data Entry Skill Test.',
        syllabusLink: 'https://ssc.nic.in/',
        applyLink: 'https://ssc.nic.in/',
        notificationLink: 'https://ssc.nic.in/',
        registrationStartDate: new Date('2025-03-01'),
        registrationLastDate: new Date('2025-03-31'),
        examDate: new Date('2025-07-15'),
        admitCardDate: new Date('2025-07-01'),
        resultDate: new Date('2025-10-01'),
        status: 'Upcoming',
        notification: 'Upcoming',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'IBPS PO 2025',
        organization: 'Institute of Banking Personnel Selection',
        category: 'Banking',
        description: 'Probationary Officer recruitment exam for public sector banks. Selection through Prelims, Mains, and Interview stages.',
        eligibility: 'Graduation in any discipline. Age: 20-30 years.',
        examPattern: 'Prelims: English, Quant, Reasoning. Mains: GA, Computer, Data Analysis, English, Reasoning.',
        syllabusLink: 'https://www.ibps.in/',
        applyLink: 'https://www.ibps.in/',
        notificationLink: 'https://www.ibps.in/',
        registrationStartDate: new Date('2025-04-01'),
        registrationLastDate: new Date('2025-04-30'),
        examDate: new Date('2025-08-20'),
        admitCardDate: new Date('2025-08-05'),
        resultDate: new Date('2025-11-01'),
        status: 'Upcoming',
        notification: 'Upcoming',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'RRB NTPC 2025',
        organization: 'Railway Recruitment Board',
        category: 'Railways',
        description: 'Non-Technical Popular Categories recruitment for various posts in Indian Railways including Clerk, Typist, Traffic Assistant, and Goods Guard.',
        eligibility: '12th pass or Graduate depending on post. Age: 18-33 years.',
        examPattern: 'CBT Stage 1: General Awareness, Mathematics, General Intelligence. CBT Stage 2: Subject-specific.',
        syllabusLink: 'https://rrbcdg.gov.in/',
        applyLink: 'https://rrbcdg.gov.in/',
        notificationLink: 'https://rrbcdg.gov.in/',
        registrationStartDate: new Date('2025-05-01'),
        registrationLastDate: new Date('2025-05-31'),
        examDate: new Date('2025-09-15'),
        admitCardDate: new Date('2025-09-01'),
        resultDate: new Date('2025-12-01'),
        status: 'Upcoming',
        notification: 'Upcoming',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'SBI PO 2025',
        organization: 'State Bank of India',
        category: 'Banking',
        description: 'Probationary Officer recruitment in State Bank of India. One of the most sought-after banking jobs in India with excellent career growth.',
        eligibility: 'Graduation in any discipline. Age: 21-30 years.',
        examPattern: 'Prelims: English, Quant, Reasoning. Mains: Data Analysis, Reasoning, English, GA, Computer.',
        syllabusLink: 'https://sbi.co.in/web/careers',
        applyLink: 'https://sbi.co.in/web/careers',
        notificationLink: 'https://sbi.co.in/web/careers',
        registrationStartDate: new Date('2025-03-15'),
        registrationLastDate: new Date('2025-04-14'),
        examDate: new Date('2025-07-30'),
        admitCardDate: new Date('2025-07-15'),
        resultDate: new Date('2025-10-15'),
        status: 'Active',
        notification: 'Active-Form',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'UPPSC PCS 2025',
        organization: 'Uttar Pradesh Public Service Commission',
        category: 'State-PSC',
        description: 'Provincial Civil Services exam for recruitment to administrative posts in Uttar Pradesh government. Similar pattern to UPSC but state-level.',
        eligibility: 'Graduate degree. Age: 21-40 years. Must be Indian citizen.',
        examPattern: 'Prelims: 2 papers (GS + CSAT). Mains: 8 descriptive papers. Interview: 100 marks.',
        syllabusLink: 'https://uppsc.up.nic.in/',
        applyLink: 'https://uppsc.up.nic.in/',
        notificationLink: 'https://uppsc.up.nic.in/',
        registrationStartDate: new Date('2025-02-15'),
        registrationLastDate: new Date('2025-03-15'),
        examDate: new Date('2025-06-20'),
        admitCardDate: new Date('2025-06-05'),
        resultDate: new Date('2025-09-30'),
        status: 'Active',
        notification: 'Closing-Soon',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'NDA & NA Examination II 2025',
        organization: 'Union Public Service Commission',
        category: 'Defence',
        description: 'National Defence Academy and Naval Academy examination for recruitment to Army, Navy, and Air Force wings of NDA.',
        eligibility: '12th pass (10+2 pattern). Age: 16.5-19.5 years. Only male candidates.',
        examPattern: 'Mathematics (300 marks) and General Ability Test (600 marks). Followed by SSB interview.',
        syllabusLink: 'https://upsc.gov.in/examinations/syllabus',
        applyLink: 'https://upsconline.nic.in/',
        notificationLink: 'https://upsc.gov.in/',
        registrationStartDate: new Date('2025-05-15'),
        registrationLastDate: new Date('2025-06-04'),
        examDate: new Date('2025-09-14'),
        admitCardDate: new Date('2025-08-25'),
        resultDate: new Date('2025-11-30'),
        status: 'Upcoming',
        notification: 'Upcoming',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'CTET 2025',
        organization: 'Central Board of Secondary Education',
        category: 'Teaching',
        description: 'Central Teacher Eligibility Test for appointment as teacher for classes I to VIII in central government schools.',
        eligibility: 'Senior Secondary with 50% marks and B.Ed/D.Ed for Paper I. Graduation with B.Ed for Paper II.',
        examPattern: 'Paper I: Child Development, Language I & II, Mathematics, Environmental Studies. Paper II: Subject-specific.',
        syllabusLink: 'https://ctet.nic.in/',
        applyLink: 'https://ctet.nic.in/',
        notificationLink: 'https://ctet.nic.in/',
        registrationStartDate: new Date('2025-04-01'),
        registrationLastDate: new Date('2025-04-30'),
        examDate: new Date('2025-07-20'),
        admitCardDate: new Date('2025-07-05'),
        resultDate: new Date('2025-09-15'),
        status: 'Upcoming',
        notification: 'Upcoming',
        isNewlyAdded: true,
        isActive: true,
    },
    {
        examTitle: 'JEE Main 2025',
        organization: 'National Testing Agency',
        category: 'Entrance',
        description: 'Joint Entrance Examination for admission to B.Tech/B.E programs in NITs, IIITs, and other centrally funded technical institutions.',
        eligibility: '12th pass with Physics, Chemistry, Mathematics. Age: No limit.',
        examPattern: 'Paper 1: Physics, Chemistry, Mathematics (MCQs + Numerical). Computer-based test.',
        syllabusLink: 'https://jeemain.nta.nic.in/',
        applyLink: 'https://jeemain.nta.nic.in/',
        notificationLink: 'https://jeemain.nta.nic.in/',
        registrationStartDate: new Date('2025-01-01'),
        registrationLastDate: new Date('2025-01-31'),
        examDate: new Date('2025-04-01'),
        admitCardDate: new Date('2025-03-20'),
        resultDate: new Date('2025-04-25'),
        status: 'Closed',
        notification: 'Result-Declared',
        isNewlyAdded: false,
        isActive: true,
    },
    {
        examTitle: 'CAT 2025',
        organization: 'Indian Institute of Management',
        category: 'Entrance',
        description: 'Common Admission Test for admission to MBA programs in IIMs and other top business schools in India.',
        eligibility: 'Bachelor\'s degree with 50% marks (45% for SC/ST). No age limit.',
        examPattern: 'VARC (Verbal), DILR (Data Interpretation), QA (Quantitative Ability). 2-hour computer-based test.',
        syllabusLink: 'https://iimcat.ac.in/',
        applyLink: 'https://iimcat.ac.in/',
        notificationLink: 'https://iimcat.ac.in/',
        registrationStartDate: new Date('2025-08-01'),
        registrationLastDate: new Date('2025-09-20'),
        examDate: new Date('2025-11-30'),
        admitCardDate: new Date('2025-11-15'),
        resultDate: new Date('2026-01-05'),
        status: 'Upcoming',
        notification: 'Upcoming',
        isNewlyAdded: true,
        isActive: true,
    },
];

// Seed function
const seedDatabase = async () => {
    try {
        console.log('🌱 Starting database seeding...');

        // Connect to MongoDB
        await mongoose.connect(mongoURI);
        console.log('✅ Connected to MongoDB');

        // Clear existing data
        await Opportunity.deleteMany({});
        await Exam.deleteMany({});
        console.log('🗑️  Cleared existing data');

        // Insert opportunities
        const insertedOpportunities = await Opportunity.insertMany([
            ...internshipsData,
            ...jobsData,
            ...coursesData,
        ]);
        console.log(`✅ Inserted ${insertedOpportunities.length} opportunities`);

        // Insert exams
        const insertedExams = await Exam.insertMany(examsData);
        console.log(`✅ Inserted ${insertedExams.length} exams`);

        console.log('🎉 Database seeding completed successfully!');
        console.log(`📊 Total records: ${insertedOpportunities.length + insertedExams.length}`);

        // Log summary
        const internshipCount = insertedOpportunities.filter(o => o.type === 'Internship').length;
        const jobCount = insertedOpportunities.filter(o => o.type === 'Job').length;
        const courseCount = insertedOpportunities.filter(o => o.type === 'Course').length;

        console.log('\n📋 Summary:');
        console.log(`   • Internships: ${internshipCount}`);
        console.log(`   • Jobs: ${jobCount}`);
        console.log(`   • Courses: ${courseCount}`);
        console.log(`   • Exams: ${insertedExams.length}`);

    } catch (error) {
        console.error('❌ Seeding failed:', error.message);
        process.exit(1);
    } finally {
        await mongoose.connection.close();
        console.log('🔌 Database connection closed');
        process.exit(0);
    }
};

// Run seeding
seedDatabase();
